format = '''
\[$username on $hostname\($localip\)\]$memory_usage $directory $git_branch $package
$character'''

[character]
success_symbol = "[♨](bold green)"
error_symbol = "[♨](bold red)"

[directory]
format = "[$path]($style)"
style = "yellow"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[package]
disabled = false
format = '[$symbol$version]($style)'

[git_branch]
format = "[$symbol](green)[$branch]($style)"
style = "italic green"
symbol = ""

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](bold red)'
trim_at = '.companyname.com'
disabled = false

[username]
disabled = false
show_always = true
style_root = 'bold red'
style_user = 'bold yellow'
format = '[$user]($style)'

[localip]
ssh_only = false
format = '[$localipv4](bold red)'
disabled = false

[memory_usage]
disabled = false
format = "MEM:[$ram_pct](bold white) SWP:[$swap_pct](bold white)"
threshold = -1

